#!/bin/bash

sudo add-apt-repository -u -y ppa:deadsnakes/ppa
sudo apt install -y python3-pip python3.6-dev python3.6-venv
sudo pip3 install --upgrade pip
sudo apt install -y build-essential libssl-dev libffi-dev python3-dev python3-venv
sudo pip install virtualenv records requests
