#!/bin/bash

TARGET=/etc/apt/sources.list.d/google-chrome.list
test ! -f ${TARGET} && sudo cat <<EOF > ${TARGET}
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
EOF

TMPFILE=`mktemp -q /tmp/$0.XXXXXX`

sudo wget -O ${TMPFILE} https://dl.google.com/linux/linux_signing_key.pub
sudo apt-key add ${TMPFILE}

sudo apt update
sudo apt install -f google-chrome-stable
